Set = set()
usrin = int (input ("Enter a number: "))
Set.add(usrin)
usrin = int (input ("Enter a number: "))
Set.add(usrin)
usrin = int (input ("Enter a number: "))
Set.add(usrin)
usrin = int (input ("Enter a number: "))
Set.add(usrin)
usrin = int (input ("Enter a number: "))
Set.add(usrin)
usrin = int (input ("Enter a number: "))
Set.add(usrin)
usrin = int (input ("Enter a number: "))
Set.add(usrin)
print ("The unique numbers are: ", Set)
print ("The length of unique numbers is: ", len(Set))
